# Generated by Django 4.1.7 on 2023-03-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
