# Generated by Django 4.1.7 on 2023-03-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
