# Generated by Django 4.1.7 on 2023-03-21 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_alter_user_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.BigIntegerField(
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(16),
                    django.core.validators.RegexValidator(regex="^\\+?1?\\d{9,15}$"),
                ]
            ),
        ),
    ]
