# Generated by Django 4.1.7 on 2023-03-21 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0005_alter_user_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.BigIntegerField(
                db_index=True,
                max_length=16,
                validators=[django.core.validators.MinValueValidator(1000000000)],
            ),
        ),
    ]
